picasso: Override AOSP reference RIL
The build inherits libreference-ril from the common vendor product, but picasso uses the proprietary QTI RIL stack through ENABLE_VENDOR_RIL_SERVICE.

On lineage-23.2, the unused AOSP reference RIL fails to build with:

  hardware/ril/reference-ril/reference-ril.c:33:10: fatal error: 'telephony/ril_cdma_sms.h' file not found

Add a product-local override module so Soong drops libreference-ril from PRODUCT_PACKAGES without touching ROM sources.

Signed-off-by: EdwardWu <bluehome.wu@gmail.com>
(cherry picked from commit 296906d771bb308770bfca56de7b533166488d88)